version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    #- dupl
    - errcheck
    - errname
    - exhaustive
    - exptostd
    - fatcontext
    # - forbidigo
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - iface
    - ineffassign
    - intrange
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    # - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - prealloc
    - recvcheck
    # - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 20
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 4
      min-occurrences: 5
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 160
      tab-width: 1
    misspell:
      locale: US
    perfsprint:
      strconcat: false
    nakedret:
      max-func-lines: 10
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - stl-go/grow-with-stl-go
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
